### ISSUE TITLE
Using fire from vendor/bin results in error.

### ISSUE THREAD

**Issue by generalredneck** [fourkitchens/fire#16]
![image](https://github.com/fourkitchens/fire/assets/526491/abdac399-fc02-4efb-9843-71180ad0c13f)

**Comment by rigoucr** [comment]
hi @generalredneck does this issue stills happening to you? I took a look and did some tests and this seems to be working fine .

**Comment by generalredneck** [comment]
@rigoucr 

So here are my steps to reproduce. I'm using the install instructions directly from the [readme](https://github.com/fourkitchens/fire?tab=readme-ov-file#install). It says I should be able to do JUST `composer require fourkitchens/fire --dev` and then run `./vendor/bin/fire init` This command now returns the following error.

Keep in mind I do not have fire installed in my $PATH variable.

![Screenshot from 2024-08-07 08-35-52](https://github.com/user-attachments/assets/c7e02159-c9d9-4ef2-bc15-73b85ea4461b)

If I create the init file manually... and look at list, there is no longer an init command.
![image](https://github.com/user-attachments/assets/a90add2d-9ea0-4ab6-8e4a-81a3f9be41df)
Additionally I have version 2.0.6 installed and it's showing 2.0.0 in the list command
![image](https://github.com/user-attachments/assets/944c3229-e4b9-4c13-b3f6-89f6e709b57b)

Lastly, if I run ./vendor/bin/fire build, I get the following
![image](https://github.com/user-attachments/assets/0359b562-470a-4734-9c31-3d9fcc910475)

So yes, I can reproduce the problem.

I expect to be able to use the program the way the README describes which says:
![image](https://github.com/user-attachments/assets/c7355a7d-b5e7-406d-b86c-9dc165aae507)

**Comment by rigoucr** [comment]
thx @generalredneck this issue had been solver over this release: https://github.com/fourkitchens/fire/releases/tag/2.0.7
